### ISSUE TITLE
Request: Powershell

### ISSUE THREAD

**Issue by vdias** [elvirbrk/NoteHighlight2016#100]
Could you please add powershell markup?

**Comment by nem8** [comment]
What do you mean, powershell is there..

**Comment by drizzoz** [comment]
I can't see it either. I just installed it today;
![image](https://user-images.githubusercontent.com/24141350/66467344-9a7d5b00-ea84-11e9-839a-95f4ad0472e5.png)

**Comment by davidszpak** [comment]
You can enable powershell and other languages in the **"ribbon.xml"** file in the default installation folder: C:\Program Files (x86)\CodingRoad\NoteHighlight2016\ or C:\Program Files\CodingRoad\NoteHighlight2016\

'<button id="buttonPowerShell" label="PowerShell" size="large" screentip="Enter PowerShell Code" onAction="AddInButtonClicked" tag="ps1"  image="Other.png" visible="true"/>

**Comment by elvirbrk** [comment]
PoweShell added as default in version 3.7
