### ISSUE TITLE
请问有支持TypeScript的打算吗？

### ISSUE THREAD

**Issue by hankuksui** [elvirbrk/NoteHighlight2016#105]
ts、vb等等有打算支持吗？

**Comment by neman-pcas** [comment]
Yes please!

**Comment by ZhangAngus** [comment]
It has already supported, please edit the settings in the xml setting file.

**Comment by elvirbrk** [comment]
TypeScript added, but not enabled by default.
See https://github.com/elvirbrk/NoteHighlight2016#additional-languages for instruction on how to enable additional language.
