### ISSUE TITLE
OneNote Dark mode compatibility

### ISSUE THREAD

**Issue by natbrood** [elvirbrk/NoteHighlight2016#109]
It's been a while since Microsoft allowed people to use the night theme of OneNote.
As of right now, to get the proper color, I need to switch back to light mode and then, after importing, I need to switch back to dark mode. 

Could dark mode compatibility be a future option?

**Comment by ahmet-cetinkaya** [comment]
I think it should be added as well.

**Comment by iamhammer** [comment]
I would love to see Dark Mode support also.

If the Office Theme is set to Black (Dark Mode) there is an additional option in the View Tab on the ribbon. It's in the Page Setup group and is labeled Switch Background.
![image](https://user-images.githubusercontent.com/1703116/73324989-d5b1be80-421a-11ea-965f-2a9bce794246.png)

This will toggle the page contents and colors between light and dark mode but not change the chrome of the application or effect the Office Theme at large (as used by other Office Apps).

![image](https://user-images.githubusercontent.com/1703116/73325180-77391000-421b-11ea-88f4-ee27cdf3f697.png)

The registry value for this is found at
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General\DarkModeCanvasLightsOn`

Changing the `DarkModeCanvasLightsOn` registry value _does_ toggle the Switch Background option. So if NoteHightlight would:

1. Check this value
2. If `DarkModeCanvasLightsOn` = 0 (off, display page content in dark mode) set it to 1 (Lights On, display page content in light mode)
3. Run the normal highlighting process
4. If `DarkModeCanvasLightsOn` was originally = 0, after highlighting set back to 0
5. All of the colors should be correctly configured and displayed now in either mode.

One other thing to account for though is that setting the registry value for `DarkModeCanvasLightsOn` will make an immediate change (just like clicking the button in the View tab), except it will not apply to the OneNote Outline Elements that have an insertion point. 

![image](https://user-images.githubusercontent.com/1703116/73325761-a9e40800-421d-11ea-9497-6d9744652d57.png)
Above: An example of a page that was selected when LightsOn was changed from 0 to 1 via the registry. The page background changed from black to white, but the actual textbox and it's contents that contained the insertion point remained unchanged.

![image](https://user-images.githubusercontent.com/1703116/73326127-1ad7ef80-421f-11ea-8856-16ae92df8a20.png)
Above: An example of a page that had selected text when LightsOn was changed from 1 to 0 via the registry. The same effect as above but additionally the paragraph that contained the selected text has it's font colors augmented.

**Comment by NickolasJohnson** [comment]
So, this is a bit strange but if you switch the background to light mode, then use notehighlight and the bright style, then switch back to darkmode it looks fine. If you stay in dark mode, then use notehightlight, it makes the text all way too dark. Pic below for comparison.
![image](https://user-images.githubusercontent.com/7981329/76321053-7f22b000-62af-11ea-9a3b-08d852ce090b.png)

**Comment by Sahil-h-3me** [comment]
> So, this is a bit strange but if you switch the background to light mode, then use notehighlight and the bright style, then switch back to darkmode it looks fine. If you stay in dark mode, then use notehightlight, it makes the text all way too dark. Pic below for comparison.
> ![image](https://user-images.githubusercontent.com/7981329/76321053-7f22b000-62af-11ea-9a3b-08d852ce090b.png)
Strange when I tried that it didn't do anything. Also I'm finding even with turning off dark mode the colours are really washed out and hard to read. I'm using OneNote 2016.

**Comment by roflbofl322** [comment]
The work around for this is to click "Switch background" -> write down the code -> switch back to dark mode.
![image](https://user-images.githubusercontent.com/32984176/80366635-40ae7800-8892-11ea-8760-fbb186cf5d5b.png)

**Comment by Sahil-h-3me** [comment]
Super weird work around but it works when you switch to light mode, write the code and then switch back to dark. Is there any plans to update this so we don't have to do that?

**Comment by wuwao1** [comment]
According to iamhammer's comments, I modified the 3.6 version of the source code with VS2017, and now my OneNote can work properly, no need to do extra operations.You can back up your NoteHighlightAddin.dll and try this 
[NoteHighlightAddin.dll](https://github.com/wuwao1/NoteHighlight2016/releases/tag/3.6.1).
![image](https://user-images.githubusercontent.com/29857592/92320960-501baa00-f058-11ea-8b4d-8e8c15c36263.png)

**Comment by wuwao1** [comment]
According to iamhammer's comments, I modified the Version 3.6 source code with VS2017, and now my OneNote can work properly in Dark Mode, no need to do extra operations.You can back up your NoteHighlightAddin.dll and try this 
[NoteHighlightAddin.dll](https://github.com/wuwao1/NoteHighlight2016/releases/tag/3.6.1).
![1](https://user-images.githubusercontent.com/29857592/92321125-1c418400-f05a-11ea-88f3-6f9b6ac5f3f1.png)


> I would love to see Dark Mode support also.
> 
> If the Office Theme is set to Black (Dark Mode) there is an additional option in the View Tab on the ribbon. It's in the Page Setup group and is labeled Switch Background.
> ![image](https://user-images.githubusercontent.com/1703116/73324989-d5b1be80-421a-11ea-965f-2a9bce794246.png)
> 
> This will toggle the page contents and colors between light and dark mode but not change the chrome of the application or effect the Office Theme at large (as used by other Office Apps).
> 
> ![image](https://user-images.githubusercontent.com/1703116/73325180-77391000-421b-11ea-88f4-ee27cdf3f697.png)
> 
> The registry value for this is found at
> `Computer\HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General\DarkModeCanvasLightsOn`
> 
> Changing the `DarkModeCanvasLightsOn` registry value _does_ toggle the Switch Background option. So if NoteHightlight would:
> 
> 1. Check this value
> 2. If `DarkModeCanvasLightsOn` = 0 (off, display page content in dark mode) set it to 1 (Lights On, display page content in light mode)
> 3. Run the normal highlighting process
> 4. If `DarkModeCanvasLightsOn` was originally = 0, after highlighting set back to 0
> 5. All of the colors should be correctly configured and displayed now in either mode.
> 
> One other thing to account for though is that setting the registry value for `DarkModeCanvasLightsOn` will make an immediate change (just like clicking the button in the View tab), except it will not apply to the OneNote Outline Elements that have an insertion point.
> 
> ![image](https://user-images.githubusercontent.com/1703116/73325761-a9e40800-421d-11ea-9497-6d9744652d57.png)
> Above: An example of a page that was selected when LightsOn was changed from 0 to 1 via the registry. The page background changed from black to white, but the actual textbox and it's contents that contained the insertion point remained unchanged.
> 
> ![image](https://user-images.githubusercontent.com/1703116/73326127-1ad7ef80-421f-11ea-8856-16ae92df8a20.png)
> Above: An example of a page that had selected text when LightsOn was changed from 1 to 0 via the registry. The same effect as above but additionally the paragraph that contained the selected text has it's font colors augmented.

**Comment by iamhammer** [comment]
What happened to the comments by @wuwao1 from Sep 6th, about a Dark Mode fix they'd made? Did it run afoul as their fix was replacing an assembly instead of issuing a pull request?

**Comment by wuwao1** [comment]
@iamhammer ,Based on your comment, I wrote the following code,FYR.Thanks.
/////////////////////////////////////////////////////////////////////////////////////////
        private void shellExcuteStr(string boolDarkModeCanvasLightsOn)
        {
            Process p = new Process();
            p.StartInfo.FileName = "cmd.exe";
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardInput = true;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardError = true;
            p.StartInfo.CreateNoWindow = true;
            p.Start();

            string strCMD = boolDarkModeCanvasLightsOn;
            p.StandardInput.WriteLine(strCMD + " & exit");

            p.StandardInput.AutoFlush = true;

            p.WaitForExit();
            p.Close();
        }
///////////////////////////////////////////////////////////////////////////////////////////////////
string boolDarkModeCanvasLightsOn1 = @"reg add HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General /v DarkModeCanvasLightsOn /t REG_DWORD /d 1 /f";
shellExcuteStr(boolDarkModeCanvasLightsOn1);
//////////////////////////////////////////////////////////////////////////////////////////////////////
string boolDarkModeCanvasLightsOn = @"reg add HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General /v DarkModeCanvasLightsOn /t REG_DWORD /d 0 /f";
shellExcuteStr(boolDarkModeCanvasLightsOn);

As for the code I modified, the personal test results were not very good and were not submitted, so I deleted them.

**Comment by wuwao1** [comment]
@iamhammer ,Based on your comment, I wrote the following code,FYR.Thanks.
`/////////////////////////////////////////////////////////////////////////////////////////
private void shellExcuteStr(string boolDarkModeCanvasLightsOn)
{
Process p = new Process();
p.StartInfo.FileName = "cmd.exe";
p.StartInfo.UseShellExecute = false;
p.StartInfo.RedirectStandardInput = true;
p.StartInfo.RedirectStandardOutput = true;
p.StartInfo.RedirectStandardError = true;
p.StartInfo.CreateNoWindow = true;
p.Start();

        string strCMD = boolDarkModeCanvasLightsOn;
        p.StandardInput.WriteLine(strCMD + " & exit");

        p.StandardInput.AutoFlush = true;

        p.WaitForExit();
        p.Close();
    }
///////////////////////////////////////////////////////////////////////////////////////////////////
string boolDarkModeCanvasLightsOn1 = @"reg add HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General /v DarkModeCanvasLightsOn /t REG_DWORD /d 1 /f";
shellExcuteStr(boolDarkModeCanvasLightsOn1);
//////////////////////////////////////////////////////////////////////////////////////////////////////
string boolDarkModeCanvasLightsOn = @"reg add HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General /v DarkModeCanvasLightsOn /t REG_DWORD /d 0 /f";
shellExcuteStr(boolDarkModeCanvasLightsOn);
`
As for the code I modified, the personal test results were not very good and were not submitted, so I deleted them.

**Comment by wuwao1** [comment]
@iamhammer ,Based on your comment, I wrote the following code,FYR.Thanks.

/////////////////////////////////////////////////////////////////////////////////////////
private void shellExcuteStr(string boolDarkModeCanvasLightsOn)
{
    Process p = new Process();
    p.StartInfo.FileName = "cmd.exe";
    p.StartInfo.UseShellExecute = false;
    p.StartInfo.RedirectStandardInput = true;
    p.StartInfo.RedirectStandardOutput = true;
    p.StartInfo.RedirectStandardError = true;
    p.StartInfo.CreateNoWindow = true;
    p.Start();
    string strCMD = boolDarkModeCanvasLightsOn;
    p.StandardInput.WriteLine(strCMD + " & exit");
    p.StandardInput.AutoFlush = true;
    p.WaitForExit();
    p.Close();
}
///////////////////////////////////////////////////////////////////////////////////////////////////
    string boolDarkModeCanvasLightsOn1 = @"reg add HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General /v DarkModeCanvasLightsOn /t REG_DWORD /d 1 /f";
    shellExcuteStr(boolDarkModeCanvasLightsOn1);
//////////////////////////////////////////////////////////////////////////////////////////////////////
    string boolDarkModeCanvasLightsOn = @"reg add HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\OneNote\General /vDarkModeCanvasLightsOn /t REG_DWORD /d 0 /f";
    shellExcuteStr(boolDarkModeCanvasLightsOn);

As for the code I modified, the personal test results were not very good and were not submitted, so I deleted them.

**Comment by elvirbrk** [comment]
Dark mode support added to version 3.7
