### ISSUE TITLE
Does not work on OneNote Version 16001.12624.20042.0

### ISSUE THREAD

**Issue by netMaReck** [elvirbrk/NoteHighlight2016#117]
Installation prozess works well.
But nothing apperas in OneNote Version 16001.12624.20042.0

**Comment by abichandani** [comment]
Same here. Nothing appears in Version 16001.12624.20042.0
Need a fix for this.

**Comment by Ciferqwq** [comment]
in copyright  16001.12827.20182.0 doesn't work

**Comment by joaociocca** [comment]
Same thing on 16001.13127.20190.0

**Comment by agentKnipe** [comment]
Same issue in 16.0.13231.20110 
this used to work, now the option is missing from the ribbon.

**Comment by elvirbrk** [comment]
Versions starting with 16001 are Onenote for windows 10 which are not supported, see #87
