### ISSUE TITLE
Fonts with spaces ignored

### ISSUE THREAD

**Issue by john-oegen** [elvirbrk/NoteHighlight2016#12]
It may be just me but I noticed this in the last release too. 
The default font used to be 'Courier New' and set fine. However now the code comes in formatted as 'Calibri', but when you look at the selected font it says 'Courier' (note not 'courier new'). It looks like it just throws away everything after the space and uses the space as a delimiter. 

My workaround has been to use 'Consolas' by setting the value here:
NoteHighlightAddin.dll.config
`Line 41:      <add Name="Font" Key="-k" Value="Consolas"/>`

**Comment by elvirbrk** [comment]
Thanks for noticing. I remember solving this issue before, so it's probably some bug introduced in later releases.

**Comment by john-oegen** [comment]
No problem, sorry to pick holes in your project. I hope you don't mind. It's a really great project you have here and I've never had such prompt feedback and frequent updates so thank you!
Cheers

**Comment by elvirbrk** [comment]
Of course I don't mind, great feedback is always valuable. For now, you are project lead QA engineer 🥇 :)
Anyway, this issue is resolved in v3.0.

**Comment by john-oegen** [comment]
Haha, thank you! Really good to be able to discuss bugs and get them sorted in an open way. I was just checking we were on the same page. 👍
