### ISSUE TITLE
bug .bat.lang is not right

### ISSUE THREAD

**Issue by kvii2202** [elvirbrk/NoteHighlight2016#120]
# bug .bat.lang is not right

不怎么会英语，将就看吧
bat.lang 的 commits 项不对，导致使用 DOS 渲染 .bat 代码时不能正确渲染注释

## 正确
、、、
Comments={
  { Block=false,
    Delimiter= { [[(rem|Rem|REM)]] },
  },
  { Block=false,
    Delimiter= { [[::]] },
  }
}
、、、

## 原文（大概？忘记备份了）
、、、
Comments={
  { Block=false,
    Delimiter= { [^[(rem|Rem|REM)*]] },
    此处不应有  ^ 和 *
  },
  此处多了个 ,
}
、、、

## 另
java 10 版本及以上中支持 `var` 关键字了

**Comment by elvirbrk** [comment]
Try version 3.7 to see if issue is fixed.
