### ISSUE TITLE
Not all of the code is copied to the clipboard leading to trailing code to be not copied 

### ISSUE THREAD

**Issue by Aravind55597** [elvirbrk/NoteHighlight2016#125]
To reproduce the issue:
1) Copy this code 

[sample python code.txt](https://github.com/elvirbrk/NoteHighlight2016/files/5034911/sample.python.code.txt)

2) Paste on the python section of notehighlight and tick 'Copy to Clipboard' and untick 'Line Number'

3) Click ok on the python window and right click and paste on onenote

**Comment by elvirbrk** [comment]
Fixed in version 3.7
