### ISSUE TITLE
[ Freature Request ] Add setting to change default color

### ISSUE THREAD

**Issue by DerDomml** [elvirbrk/NoteHighlight2016#132]
Hi elvirbrk and everyone collaborating on this!
I really love the extension. It makes syntax highlighting in OneNote so much smoother than copying it into word and back into Note or comparable nerv-wreckening operations..
The only thing I wish I could find in the settings is to select a color for default text though. (Text that is not recognized by the selected language or just the default text for the code that is not particularly highlighted)
The issue with this is for me that my Note in dark theme now has this light grey text on top of a slightly darker grey background and it is a pain to read it.
Despite for actual code highlighting, I use the extension for formatting block of cmd, powershell and git commands as well. As you can see, readability then in dark mode isn't great:
![image](https://user-images.githubusercontent.com/43981618/96475533-6d858b80-1234-11eb-9c97-ed82b92dd44a.png)

Thanks for your work and best wishes
Domml

**Comment by elvirbrk** [comment]
You can change style and choose one with suitable colors. Or you can edit existing style by changing style parameters in C:\Program Files\CodingRoad\NoteHighlight2016\highlight\themes

**Comment by elvirbrk** [comment]
Dark theme is supported in version 3.7 so check it out.
