### ISSUE TITLE
Dark mode - code not readable

### ISSUE THREAD

**Issue by pgrass** [elvirbrk/NoteHighlight2016#133]
Hi,
Could you please consider adjusting how text is displayed in dark mode? 
First picture shows text pasted when not in the dark mode.
Second picture shows text pasted when in the dark mode.

When I'm not in the dark mode and paste code and then switch to the dark mode, the text displays nicely (picture 1). However if I try to paste code while in the dark mode (picture 2) the text is not readable.

Could you please help me with the solution?
Thank you!

Best Regards,
Piotr

![image](https://user-images.githubusercontent.com/17457272/99156090-9d527280-26be-11eb-8b8b-e7d24d1b24d6.png)
![image](https://user-images.githubusercontent.com/17457272/99156097-ad6a5200-26be-11eb-9a88-05258c298772.png)

**Comment by elvirbrk** [comment]
Dark mode support added to version 3.7
