### ISSUE TITLE
Odd squares showing up

### ISSUE THREAD

**Issue by dollvader** [elvirbrk/NoteHighlight2016#14]
When adding code with no line numbers, I am getting squares where the line numbers should be.  When I do have line numbers, they show up just fine but I still get a square around the "N" in namespace.  See picture for clarification.
![capture](https://user-images.githubusercontent.com/30845243/29093684-4312dd8a-7c50-11e7-9b00-e66220988741.JPG)
![capture2](https://user-images.githubusercontent.com/30845243/29093802-b9a98322-7c50-11e7-8f73-fb2ad74444bb.JPG)

I am using OneNote 2013 32-bit so this may just be an incompatibility issue on my end.

**Comment by elvirbrk** [comment]
Please export whole page and attach it. So I can import it in OneNote 2016 and see if it's rendered ok.
It probably is some unsupported feature in ON 2013.

**Comment by dollvader** [comment]
Here you go.
[Test.zip](https://github.com/elvirbrk/NoteHighlight2016/files/1212048/Test.zip)

**Comment by elvirbrk** [comment]
Unfortunately, your page is rendered just fine in OneNote 2016, so it seems ON 2013 has some issue with page format.
Can you try one more thing. Create one more test page (or use same if you kept it), and create same export. After that, manually edit those squares, so the page would look the way it's supposed to, and then export that. Hopefully I will be able to compare what's different after edit and discover what is causing problems.

**Comment by dollvader** [comment]
I was able to replace the boxes with spaces for the clipping without line numbers.  However, I could not remove the box in the clipping with line numbers.  I tried typing over it and deleting and inserting a new letter but the box remained in both cases.  I did notice that when I highlighted the text the box disappeared.
![nobox](https://user-images.githubusercontent.com/30845243/29191603-eb14e4bc-7de3-11e7-86c6-ce66a6c5ec9c.JPG)
[Test 2-edit.zip](https://github.com/elvirbrk/NoteHighlight2016/files/1216375/Test.2-edit.zip)

**Comment by elvirbrk** [comment]
I analyzed this issue, but I couldn't find a way around it.
No matter what I tried, OneNote always inserts additional "empty" character at the beginning of my text.
That empty character is ignored in 2016 version, but it obviously causes issue in 2013.

One last thing I can think of is that you could try one of earlier versions (like v2.0 or v2.1) to see if this issue is maybe introduced with some fancy formatting in later versions.

**Comment by elvirbrk** [comment]
I think I finally cracked this issue. Please try v3.2, it should be OK now.
