### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by ArsLoViBre** [elvirbrk/NoteHighlight2016#18]
Sorry for stupid question, I'm newcomer here, but how to install it on my PC? I downloaded zip package, but there isn't any .msi files at all. In instruction you wrote "To install just run MSI file from releases. For Office 64-bit use NoteHighlight2016.msi", but I cannot see one. What do I wrong?

**Comment by javae** [comment]
Check the releases tab: https://github.com/elvirbrk/NoteHighlight2016/releases

**Comment by elvirbrk** [comment]
There are no stupid questions :)
Thanks for pointing part of instructions that was not clear.
Anyway, I updated instructions, so there is a link, just like @javae pointed out.
