### ISSUE TITLE
Missing Feature: Boxing IN

### ISSUE THREAD

**Issue by Methlodis** [elvirbrk/NoteHighlight2016#2]
Was wondering if a feature for shading in the background for a text, and boxing it in could be added. Would help users differentiate their code from other work. As well as the ability to segment the code from the line indicators. 

Great job on this by the way!

**Comment by elvirbrk** [comment]
Could you manually create some examples for shading and boxing in OneNote and send screenshots so I can have a clear picture of what you mean.
I'll look into it and see what can be done.

**Comment by elvirbrk** [comment]
Implemented in v2.2
