### ISSUE TITLE
Cannot install new version

### ISSUE THREAD

**Issue by SongRb** [elvirbrk/NoteHighlight2016#20]
I have cloned your source code in order to learn OneNote Addin Development. Unfortunately, after changing some text in the form(Change "OK" button to "OK-1") and build&install, I cannot see any changes. The addin seems has not updated(I had already uninstall the previous addin!). It appears that my Office addin is binded with mscoree.dll, not the installation folder like `C:\Program Files\CodingRoad\NoteHighlight2016`. I love OneNote and want to contribute to your addin project. I wonder if there are any help.  
Using OneNote 2016 64bit on Windows 10.0.15063.632 64bit.  
![image](https://user-images.githubusercontent.com/15308237/31061059-9a3d460c-a74f-11e7-9dbd-d57888ac6371.png)

**Comment by elvirbrk** [comment]
First of all you are welcome to get involved into development.
If you are still having issues with build or install, I can try to check my development setup to see if we can make it work.
For me is also shows that it's binded with mscoree.dll, so I guess that's normal.
If you managed to get addin to load inside OneNote, than you already solved hard part.
