### ISSUE TITLE
Feature Request - Ignore Spelling for Code Highlight

### ISSUE THREAD

**Issue by gomker** [elvirbrk/NoteHighlight2016#21]
Not sure if there is an easy way to achieve this but it would be nice to have spell check ignore Code Highlighted snippets.

Thanks for the work you have done on this plugin, I find it very useful.

Regards,

**Comment by elvirbrk** [comment]
I'll check it out to see if it's possible to implement.

**Comment by elvirbrk** [comment]
Fixed in v3.1
