### ISSUE TITLE
Feature request: change default font for code

### ISSUE THREAD

**Issue by stefanuddenberg** [elvirbrk/NoteHighlight2016#22]
It would be nice to change the default from Courier New to something else (e.g., Monaco)!

**Comment by elvirbrk** [comment]
You can change font in config file in installation folder. Default path is "C:\Program Files\CodingRoad\NoteHighlight2016\NoteHighlightAddin.dll.config".
There you will find entry for font:
\<add Name="Font" Key="-k" Value="Courier New"/>
Just change it as you like.
