### ISSUE TITLE
Red squiggly underline in OneNote

### ISSUE THREAD

**Issue by Masum06** [elvirbrk/NoteHighlight2016#24]
Thank you for this Awesome add-in. This is a OneNote issue, not NoteHighlight2016, but I am hoping you can help. 
The inserted code is shown with a squiggly underline in OneNote, meaning a spelling error. The only way I know to disable it permanently is to add the code syntax to Dictionary, which is a hectic work to do for every code syntax. Can you make it automatic? Or any other solution to this?
Thanks in advance!

**Comment by elvirbrk** [comment]
See #21
