### ISSUE TITLE
Disabling 'line number' adds lang=la randomly into the code

### ISSUE THREAD

**Issue by VonSchnitzel** [elvirbrk/NoteHighlight2016#25]
When entering new code in the pop up box or selecting existing text and clicking on a language, when deselecting the line number option, it will then randomly add 'lang=la﻿' between the text after it's been added.

**Comment by elvirbrk** [comment]
I'll have a look at it, probably some bug introduced with spell check ignore feature.

**Comment by elvirbrk** [comment]
Fixed in v3.2

**Comment by VonSchnitzel** [comment]
Wow, that's awesome! Thank you so much elvirbrk,

**Comment by elvirbrk** [comment]
You're welcome.
