### ISSUE TITLE
Using T-SQL in the SQL formatter

### ISSUE THREAD

**Issue by AnandaSim** [elvirbrk/NoteHighlight2016#26]
If I have the original expression 
   **WHERE COUNTRY='Germany'**
the SQL formatter turns this into
   **WHERE COUNTRY=apos;Germanyapos;**
if I choose the Clipboard Output. It does not happen in the Box output.

**Comment by elvirbrk** [comment]
I'll check it out, this apostrophe issue keeps coming back for some reason.

**Comment by elvirbrk** [comment]
Fixed in v3.2

**Comment by AnandaSim** [comment]
Thank you

Ananda

Ananda Sim
mailto:anandasim@gmail.com
LinkedIn: https://www.linkedin.com/in/anandasim/
Microsoft Office Resources: http://TheNewOfficeCoach.blogspot.com/
