### ISSUE TITLE
Exception when trying to convert existing text

### ISSUE THREAD

**Issue by gomker** [elvirbrk/NoteHighlight2016#28]
![image](https://user-images.githubusercontent.com/3577339/32013301-481ce1e6-b980-11e7-9c89-3f7eea9c91c0.png)

If I select some text to convert to a NoteHighlight I get the above Exception.
Copy pasting the same text into a new NoteHighlight does not cause this error.

Let me know if you want a sample text

**Comment by elvirbrk** [comment]
Please send sample text or whole OneNote page with offending text, and I'll have a look at it.
