### ISSUE TITLE
[Feature request/Enhancement] Adding an option for lines to start with the dollar symbol

### ISSUE THREAD

**Issue by VonSchnitzel** [elvirbrk/NoteHighlight2016#29]
Hope it's ok to log feature requests under 'issues'. Sorry if not!

I was wondering if it'd be possible to add an option for new lines to begin with the dollar symbol ($) rather than line numbers. So for example you'd have:

$      rename-computer -NewName NoteHighlighterRocks
$      restart-computer -Force
$      etc

I realise I could manually put the symbol in front of each line before using the highlight tool as well but figured I'd ask in case it was just a straight forward feature to implement.

**Comment by elvirbrk** [comment]
I will see if I can include something in next update.
Could you just explain if you want $ instead of line number or you want line numbers and $ sign?
Also, when you select code, do you want to select $ sign as well or only code?

**Comment by VonSchnitzel** [comment]
Thank you. Ideally it would be instead of line numbers. So rather than for example:

1   rename-computer -NewName ComputerA
2   restart-computer -Force

it would be 

$   rename-computer -NewName ComputerA
$   restart-computer -Force

When selecting code, I'd usually just select the code without the $ sign.

**Comment by elvirbrk** [comment]
Added feature in v3.3
In config file just add `LineNrReplaceCh="$"` instead of `LineNrReplaceCh=""` on this line:
`<HighLightSection FolderName="highlight" ProcessName="highlight.exe" ThemeFolder="themes" LineNrReplaceCh="">`
