### ISSUE TITLE
Losing focus when try to paste code

### ISSUE THREAD

**Issue by Insane-neal** [elvirbrk/NoteHighlight2016#30]
Can you change the focus to the editor? Right now I have to click the editor.

**Comment by elvirbrk** [comment]
I'll see what can I do about it.

**Comment by Insane-neal** [comment]
And if possible, please consider adding inline code. I'm sick of the grammar check for inline code.

**Comment by rfdunn** [comment]
Seconded, I love this addin but it would be even better if the Editor automatically popped over OneNote.

**Comment by elvirbrk** [comment]
@Insane-neal  can you elaborate this:
> And if possible, please consider adding inline code. I'm sick of the grammar check for inline code.

AFAIK grammar check is already disabled for formatted code.

**Comment by Insane-neal** [comment]
yes, grammar check for formatted code is disabled. I mean you can add a function for the inline code. 
So say I type a sentence: "Enumset is great" in OneNote. Right now if I select Enumset and click JAVA, it gives error: Exception from InsertHighlightCodeToCurrentSide. 
You can just add one button for the inline code. In Markdown, it's something like `Enumset`, with disabled grammar check.

**Comment by elvirbrk** [comment]
In v3.3 added features:
- Form focus
- Format inline code
