### ISSUE TITLE
How to change the LineNumbersunchecked for default

### ISSUE THREAD

**Issue by Behemoth-s** [elvirbrk/NoteHighlight2016#31]
## Description
I changed the NoteHighlightAddin.dll.config file like following, but it seems not working.
`    <NoteHighLightForm.Properties.Settings>
      <setting name="ShowLineNumber" serializeAs="String">
        <value>False</value>
      </setting>`     
 `<add Name="LineNumbers" Key="-l" Value="" Option="false"/>`

## System detail
Office 365 on Windows 10 x64

**Comment by elvirbrk** [comment]
It's probably a bug since it should save last used value, like other settings.
I'll have a look at it.

**Comment by elvirbrk** [comment]
Fixed in v3.3
Last values you use are saved.
