### ISSUE TITLE
How to change the word size of code generated by NoteHighlight?

### ISSUE THREAD

**Issue by DuankangFu** [elvirbrk/NoteHighlight2016#32]
The default word size of the formatted codes generated by NoteHighlight is 10, which is too small to read easily, If a function of changing default word size of codes I will really appreciate it !!!

**Comment by elvirbrk** [comment]
Nice suggestion, I will see if I can include it in next version.

**Comment by ertyz** [comment]
It will be nice. Generated font style is too small for me also

**Comment by elvirbrk** [comment]
There is new entry in config file where you can choose font size:
<add Name="FontSize" Key="-K" Value="10"/>
