### ISSUE TITLE
An Exception

### ISSUE THREAD

**Issue by DuankangFu** [elvirbrk/NoteHighlight2016#33]
The exception shows below in the picture:
https://sjtueducn-my.sharepoint.com/personal/duankangfu_sjtu_edu_cn/_layouts/15/guestaccess.aspx?docid=11a84d7b4baca4c29bd2580a11783238e&authkey=AXyACIlCROULfBXgjEBKCZ4&e=y2KnSH

**Comment by elvirbrk** [comment]
Can you send me code that you are trying to highlight, that is causing this error?

**Comment by DuankangFu** [comment]
![image](https://user-images.githubusercontent.com/25225509/34717453-232eafac-f56e-11e7-8c54-704c7e8e0363.png)
Just very normal code. And when the Exception once happened, any code will cause the exception afterwards.

**Comment by elvirbrk** [comment]
I couldn't reproduce this issue, but please check if you have same problem with last version v3.3.

**Comment by DuankangFu** [comment]
Hi, I just tried the version v3.3, but It's_ hetting more weird.....
This is the code waiting for transforming.
![image](https://user-images.githubusercontent.com/25225509/35153295-e59816b0-fd60-11e7-8a9a-a8e112b0f8df.png)
But after the transformation, only the first line is left.
![image](https://user-images.githubusercontent.com/25225509/35153345-1bea8216-fd61-11e7-8e78-3afdad66f74d.png)

**Comment by elvirbrk** [comment]
Can you export and attach page with that code.
Issue is probably caused by some non-visible characted copied along with rest of code.
