### ISSUE TITLE
Option for choosing custom themes

### ISSUE THREAD

**Issue by kevinhynes** [elvirbrk/NoteHighlight2016#35]
Hi @elvirbrk! First off thank you for creating this great tool!

Second, I am new to using GitHub so excuse me if this is not proper protocol for this request (how do I label this as a question or enhancement?)

I am considering creating my own custom theme to match some IDEs I am more familiar with using.  Is that as simple as creating a new `*.theme` file  in 
`C:\Program Files (x86)\CodingRoad\NoteHighlight2016\highlight\themes` ?

Any thoughts/hints/advice would be appreciated.  Thanks again.

**Comment by elvirbrk** [comment]
Yes, just add new file to themes folder.
Also, please look for more themes here (https://github.com/andre-simon/highlight/tree/master/themes) maybe you can find what you need.
