### ISSUE TITLE
Unable to format multiple lines

### ISSUE THREAD

**Issue by tommyvuh** [elvirbrk/NoteHighlight2016#36]
![image](https://user-images.githubusercontent.com/24283779/35298142-134e1104-0036-11e8-8bc1-c56c277554e7.png)
![image](https://user-images.githubusercontent.com/24283779/35298157-1e834404-0036-11e8-83bd-06b198ed1b94.png)
![image](https://user-images.githubusercontent.com/24283779/35298175-2586ef44-0036-11e8-9bab-9e07cdf4a331.png)

I'm not sure if this is a bug or it just hasn't been implemented yet, but I'm unable to format a piece of code by highlighting it and then selecting one of the code types. It will only ever format the first lines. Each line of code is currently separate by Shift+Enter, I've tried the same with Enter and it is the same result. So, I can only format one line at a time right now unless I type it out or use the Copy feature. 

Also, it there any way to insert a code block somewhere specifically in the page without Copying because the Copy doesn't remove Spell Check and it's inconvenient to scroll to the top each time.

**Comment by elvirbrk** [comment]
I'll take a look, probably a bug. It behaves as if lines are separated by Shift+Enter, but should work if lines are separated only with Enter.

Not sure I understand second part? If you select some text and format it, then it is formatted in same place. But if you open form somewhere else (just put cursor without selecting text), then formatted text (which you have to paste inside form) will be placed there.

**Comment by elvirbrk** [comment]
Fixed in version 3.4
