### ISSUE TITLE
Line number does not match the code

### ISSUE THREAD

**Issue by strprincess** [elvirbrk/NoteHighlight2016#37]
I found the line number does not exactly match the code,even though I changed the font size. The code likes this:
![image](https://user-images.githubusercontent.com/20025002/35319496-057bc6bc-011b-11e8-9626-b290dcbab495.png)

**Comment by elvirbrk** [comment]
Thanks for reporting, I'll look into it.

**Comment by elvirbrk** [comment]
Could you explain how you got that result. I tried to reproduce this issue, but everything looks fine.

**Comment by strprincess** [comment]
My system language is Chinese(simplified). Maybe the reason is this.

**Comment by elvirbrk** [comment]
Could you export page with that example so I can analyze what caused that offset.

**Comment by strprincess** [comment]
Sample code likes this, you can copy and paste them into your onenote.

int pre[1000];
int find(int x)           //查找根节点
{ 
    int r=x;
    while ( pre[r] != r )        //返回根节点 r
          r=pre[r];
    int i=x , j ;
    while( i != r )           //路径压缩
    {
         j = pre[i]; // 在改变上级之前用临时变量  j 记录下他的值 
         pre[i]= r ; // 把上级改为根节点
         i=j;
    }
    return r ;
}

**Comment by elvirbrk** [comment]
Now I see, because of Chinese characters in comments, those lines are taking up more space and are misaligned with line numbers.
OK, I will see what can be done about it.
