### ISSUE TITLE
Powershell_ISE syntax highlighting

### ISSUE THREAD

**Issue by neztach** [elvirbrk/NoteHighlight2016#42]
I love this addin.  I'm wondering if there's a way to replicate the powershell_ISE syntax highlighting as none of the current themes really work with powershell.

**Comment by elvirbrk** [comment]
Thanks.
You can try one of the themes here: https://github.com/andre-simon/highlight/tree/master/themes
If none of them are close enough, then you can create your own. It shuldn't be a problem to replicate Powershell ISE.
