### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by jefemagril** [elvirbrk/NoteHighlight2016#45]
Any possibility of adding support for OneNote for Mac?

**Comment by elvirbrk** [comment]
Unfortunately, AFAIK it is not possible. See also #41

**Comment by kahboom** [comment]
Still no support for macOS?

**Comment by kahboom** [comment]
Well, damn.

Nice GH profile pic though!

**Comment by elvirbrk** [comment]
Thanks ;)

**Comment by mertzjames** [comment]
So... this can be done for all platforms if you migrate to Javascript instead of using C# :/ see: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart

**Comment by elvirbrk** [comment]
There is plan for that, but right now I don't have enough time :(

**Comment by mertzjames** [comment]
Ya totally understand that.  When you do get to that point, I'm willing to help out with the testing and some development.

**Comment by SachaTe** [comment]
Any update on this, it would be great to have ?
