### ISSUE TITLE
Does using NoteHighlight2016 in a shared document mean everyone else has to use it?

### ISSUE THREAD

**Issue by aklin** [elvirbrk/NoteHighlight2016#47]
Hello! Thank you for making this awesome tool.

We've standardized on OneNote for documentation at work but we don't have a code highlight solution yet. I suggested NoteHighlight2016, but there was concern over creating a dependency for everyone.

So, what happens to annotated pages if you don't have this plugin installed? Can they be viewed normally?

I apologise if this has been asked before, couldn't find it in the Issues tab. Thank you again for making our lives easier!

**Comment by elvirbrk** [comment]
Glad you find this tool useful.
Now to answer your question, annotated pages have no dependency on this plugin, so those that only want to view code don't need to install it. This plugin is only automating what could be done by hand in OneNote like changing font, color, etc. Page rendering is done solely by OneNote.
You can uninstall plugin (temporary, of course :) ) and formatted pages will still be available.
