### ISSUE TITLE
Does it work with OneNote 2016 32-bit ?

### ISSUE THREAD

**Issue by yikuo123** [elvirbrk/NoteHighlight2016#5]

**Comment by elvirbrk** [comment]
It should work on 32-bit but I don't have 32-bit installation to try it.
If you can try and confirm, that would be great.

**Comment by GrantDuan** [comment]
I tried, it seems doesn't work

**Comment by elvirbrk** [comment]
Ok, thanks for trying.
I will see if I can setup OneNote 32-bit to test what's wrong.
In the mean time you can use NoteHighlight 2013 (https://notehighlight2013.codeplex.com), at least that should work for 2016 32-bit.

**Comment by pixelicous** [comment]
Hi,
I just found out of this addin, trying with 2016 32bit, also doesn't work here, tried uninstall reboot and again going to com addins- it cannot find it, tried browsing to the DLLs themselves, also doesnt work.

Please if you can make it work on 32bit version it would be amazing, also.. is it a problem porting this to onenote on mac? lots of work?

**Comment by jonathanweinberg** [comment]
Somewhat surprised that this is 64 bit oriented.

Can I clarify that this is intended for OneNote 2016 x64, not OneNote 2016 x86 running on an x64 system?

Microsoft is pretty clear that the x64 versions of Office software are intended to fulfill a few specific needs [Reasons to choose the 64-bit version](https://support.office.com/en-us/article/Choose-between-the-64-bit-or-32-bit-version-of-Office-2dee7807-8f95-4d0c-b5fe-6c6f49b8d261)

Excerpted from that page:

`
Reasons to choose the 64-bit version

Computers running 64-bit versions of Windows generally have more resources such as processing power and memory, than their 32-bit predecessors. Also, 64-bit applications can access more memory than 32-bit applications (up to 18.4 million Petabytes). Therefore, if your scenarios include large files and/or working with large data sets and your computer is running 64-bit version of Windows, 64-bit is the right choice when:

You’re working with large data sets, like enterprise-scale Excel workbooks with complex calculations, many pivot tables, data connections to external databases, Power Pivot, 3D Map, Power View, or Get & Transform. The 64-bit version of Office may perform better in these cases. See, Excel specifications and limits, Data Model specification and limits, and Memory usage in the 32-bit edition of Excel.

You’re working with extremely large pictures, videos, or animations in PowerPoint. The 64-bit version of Office may be better suited to handle these complex slide decks.

You’re working with files over 2 GB in Project, especially if the project has many sub-projects.

You’re developing in-house Office solutions like add-ins or document-level customization. Using the 64-bit version of Office lets you deliver a 64-bit version of those solutions as well as a 32-bit version. In-house Office solution developers should have access to the 64-bit Office 2016 for **testing and updating these solutions**.
`

**Comment by elvirbrk** [comment]
Yes, this is indeed for 64-bit OneNote.
This was not some master plan. I upgraded Office to 2016 (choose 64-bit because why not :) ) and later found out that Notehighlight2013 plugin (which I used with OneNote 2013) doesn't work anymore.
I assumed it had to do with some API changes in 2016 and tried to make it work again, so NoteHighligth2016 is born.
Anyway, I plan to make it work with 32-bit when I find some spare time.

**Comment by elvirbrk** [comment]
Added installer for 32-bit Office to releases:
https://github.com/elvirbrk/NoteHighlight2016/releases/download/v2.2/NoteHighlight2016x86.msi

**Comment by elvirbrk** [comment]
@pixelicous 
 > is it a problem porting this to onenote on mac? lots of work?

Can't say anything about this, never did anything for mac.

**Comment by pixelicous** [comment]
@elvirbrk thanks man 👍

**Comment by yikuo123** [comment]
@elvirbrk thanks very much
