### ISSUE TITLE
Anyway of getting this to work with the OneNote App?

### ISSUE THREAD

**Issue by kyfohatl** [elvirbrk/NoteHighlight2016#51]
I have the OneNote app, not the office version as I don't have office. I tried installing this extension and it doesn't show, regardless of whether I install the 32 bit or 64 bit. I had look at the at the troubleshooting links but I'm not sure if they apply to the app because it's quite different. I'm not even sure if the app has 64 and 32 bit versions - it seems like there's just the one version. Any help would be greatly appreciated.

**Comment by elvirbrk** [comment]
If you mean OneNote app from Store, then I think it's not possible because that one doesn't support add-ins.

**Comment by kyfohatl** [comment]
Ah damn. That's unfortunate. Thanks for the reply.
