### ISSUE TITLE
Feature Request: Quick highlight when selecting text

### ISSUE THREAD

**Issue by dagansandler** [elvirbrk/NoteHighlight2016#53]
Hi,
Currently when selecting text and clicking on a language, the window pops up with options for customizing the style, and after clicking "OK" the highlighting is applied as expected.
However, usually the same style is used multiple times, and so the popup window and the extra "OK" click are irrelevant.
It would be nice if after the first time configuring a language's style, then a click on that language will automatically apply the previously selected style to the selected text, or maybe allow a selection between "quick highlight" and "select highlight options"

**Comment by elvirbrk** [comment]
Nice suggestion, I'll see if I manage to include it into next version.

**Comment by elvirbrk** [comment]
Supported in v3.6
