### ISSUE TITLE
NoteHighlight2016 can‘t be installed

### ISSUE THREAD

**Issue by zjfjyc** [elvirbrk/NoteHighlight2016#59]
OS Version：Win10 Pro 1709 x64-bit
OS Build：16299.371
Onenote App Version：16.0.4456.1003 x64-bit

Description：
I download the NoteHighlight2016.mis (v3.5) file from github, and give the software full control permission of authentication. .NET 3.5 have been installed before, but I can't install this .mis file, it popped up a window and prompted that "a DLL required for this install to complete could not be run". How can I solve this problem? THX.

**Comment by elvirbrk** [comment]
Application is using .NET 4.5 so you can install it to see if that is causing the problem.
Also check Event Viewer, to see if there are some more details about error.
