### ISSUE TITLE
Styling request for sublime / MS Visual Studio Code

### ISSUE THREAD

**Issue by john-oegen** [elvirbrk/NoteHighlight2016#6]
This is a brilliant little add-in! I had the 2013 Chinese installer version but this is way more stable and still in development.
I use Sublime and MS VS Code for development. It would be a really awesome feature if I could export from Sublime to NoteHighlight and it keep the formatting from the current theme. Definitely a feature not an issue as such. Keep up the good work!

**Comment by john-oegen** [comment]
On the back of this I've had a go at creating a theme that matches roughly what my sublime theme looks like so it's familiar and is easy on the eyes. I can't see a way to change the default text color for unmatched keywords from black however. I've tried changed the "Default" and "Canvas" values to "#FFFFFF" and neither apply to what I'd call the default un-matched text. So when I use a dark, almost black/grey background for the code block the text is black and unreadable.
I also can't see a way to add new themes, only amend existing ones. Here I've butchered the bclear.theme file.

Default        = { Colour="#FFFFFF" }
Canvas         = { Colour="#FFFFFF" }
Number         = { Colour="#99FF69" }
Escape         = { Colour="#6DAD56" }
String         = { Colour="#2b83ba" }
StringPreProc  = { Colour="#2b83ba" }
BlockComment   = { Colour="#6DAD56", Italic=true }
PreProcessor   = { Colour="#620ac6" }
LineNum        = { Colour="#8F8F8F" }
Operator       = { Colour="#FFFFFF" }
LineComment = BlockComment
Interpolation  = { Colour="#CC60A3" }

Keywords = {
  { Colour= "#569CD6", Bold=true },
  { Colour= "#c42638", Bold=true },
  { Colour= "#e12f76" },
  { Colour= "#2ac749" },
}

**Comment by elvirbrk** [comment]
I don't think it is possible to export from some other tool and keep formatting, because it depends how clipboard is implemented. For example, if you copy from Visual Studio to OneNote you'll lose formatting, but if you copy from VS to Word and then from Word to OneNote formatting is kept. This is all without using NoteHighlight2016.

So, as you already figured it out, you can create similar looking theme for NoteHighlight2016 and get similar effect.
I will look into issue regarding color for unmatched text and how to create new themes.

**Comment by john-oegen** [comment]
Hey, thanks for replying. Yeah I can create a theme by modifying an existing one (overwriting the original) and changing the colours but I can't seem to add a new one by taking a copy of an existing one. Is this something I'm doing wrong or a by design thing?
Many thanks,

**Comment by elvirbrk** [comment]
Should be fixed now in version 2.3.

**Comment by john-oegen** [comment]
Brilliant! Thank you for the instant attention to fixing this. I will download an update and give it a go.
Thank you.
