### ISSUE TITLE
Inactive Add in, i cant change it to active

### ISSUE THREAD

**Issue by gladixD** [elvirbrk/NoteHighlight2016#60]
Win 10 + office 2016 64Bit

I installed the latest version of OneNoteHighlighter 2016 64bit and the installation passed. The Regestry Entrys are written. I changed the Value from HKEY_User......../..../AddIn/...../ to 3. Like your post in other Issue discription. But it is not starting the Ribbon. In the Options AddIn Tab, in the Load Behavior Description line is the message:

Not loaded. A runtime error occured duiring the loading of the COM-Add-In

Maybe you can help me to find a solution to activate the nice and needed tool :)

Thanks for help.

Best Regards gladixD

**Comment by elvirbrk** [comment]
Please try if some of solutions mentioned in #7 or #27 help.
Also, please check Event Viewer for errors, that could point you in right direction.
