### ISSUE TITLE
Can this work with OneNote for Windows 10? (not 2016)

### ISSUE THREAD

**Issue by penguinairlines** [elvirbrk/NoteHighlight2016#61]
I'm reading that there's different versions of OneNote:
OneNote for Windows 10
OneNote 2016

I have tried to install OneNote 2016, but I do not have an account with an office 2016 license.  Therefore, I figured I would ask if it is possible to make this add-on/plug-in work with OneNote for Windows 10?

**Comment by john-oegen** [comment]
You can still use OneNote 2016 without owning O365 (or at least you used to be able to! I certainly started using it before I had an Office365 license.) 

The second reply here:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_onenote-mso_win10-mso_2016/how-to-install-onenote-2016-instead-of-just/774af256-0189-4416-a7dd-29c9f77e8e09

SW
SWischner replied on  March 17, 2017
How do I install OneNote 2016 when my windows 10 computer already has the "normal" less good OneNote installed? Do I have to buy the Office package to get OneNote 2016 or are there other ways of getting it.

No you don't have to buy the Office package.

There is still a free version of OneNote 2016 Desktop available for download. It lacks the ability to save notebooks locally and all connections to MS Office like creating Outlook tasks but apart from that its the full OneNote 2016.

Microsoft has hidden the download link somewhat recently, which *could* mean, that this version will not be there forever. But as for now you still find it here:

http://www.onenote.com/download

Ignore the big message which says that you already have OneNote installed. Click on the link "Windows Desktop" under "Also available for" to download the installer.

Hope this helps you out.

**Comment by penguinairlines** [comment]
thanks @john-oegen 

however, I was able to locate this installer on my own.  The issue comes in after this, when "MyOffice" asks me to sign in to my work/school account.  I have tried to sign in here with my Microsoft account, but it simply says my password is incorrect.  I have validated that this is incorrect by logging into microsoft.com.  I believe that Microsoft is differentiating the professional accounts (volume licensed to some degree) and personal accounts, but I don't see a way to sign into MS OneNote 2016 without a professional account, as this is the only option it lists when authenticating.

**Comment by elvirbrk** [comment]
Duplicate #78

**Comment by Pete-Fowler** [comment]
> I'm reading that there's different versions of OneNote: OneNote for Windows 10 OneNote 2016
> 
> I have tried to install OneNote 2016, but I do not have an account with an office 2016 license. Therefore, I figured I would ask if it is possible to make this add-on/plug-in work with OneNote for Windows 10?

Does it work for OneNote for Windows 10 these days?

**Comment by Jenfre74** [comment]
I have One note app and one note fo windows 10. I have found the installer works great in the app but not in the windows 10 one note. I prefer the windows 10 version. Is it possible someone is already aware of what alterations i can make to make it work in windows 10?
