### ISSUE TITLE
About Kotlin support

### ISSUE THREAD

**Issue by w0330t** [elvirbrk/NoteHighlight2016#71]
I don't see Kotlin support at ribbon.xml，Can you add this function please？

**Comment by elvirbrk** [comment]
Just add this line to ribbon.xml
<button id="buttonKotlin" label="Kotlin" size="large" screentip="Enter Kotlin Code" onAction="AddInButtonClicked" tag="kotlin"  image="Other.png" visible="true"/>

I think it should work.

**Comment by w0330t** [comment]
it‘s work，Thanks for your help.
