### ISSUE TITLE
My onenote is2018,can I use this 

### ISSUE THREAD

**Issue by stillAnd** [elvirbrk/NoteHighlight2016#72]

**Comment by stillAnd** [comment]
Ok, my version is comes with system installed, it means I can't use the highlight, is this ?and i don't know if there is office's,should i go  to find it  .thank you for your reply.

**Comment by elvirbrk** [comment]
If OneNote looks something like this, then it will work:
![image](https://user-images.githubusercontent.com/20227334/45940358-f049a700-bfd8-11e8-9b92-bef9d19de7fb.png)

If it looks like this, then it will not work:
![image](https://user-images.githubusercontent.com/20227334/45940385-22f39f80-bfd9-11e8-99dc-0e16611974e1.png)

**Comment by stillAnd** [comment]
Oh...is the ffirst...sad

**Comment by rosshug** [comment]
For those that just have the OneNote for Windows app (the one from Windows Store and does not allow add-ins) but want to use  NoteHighlight, you can install the OneNote desktop version alongside the OneNote for Windows app.

I have both the app and the desktop versions installed, and they work fine together.  I mostly use the app, but if I want to highlight a code block I can do this in the desktop version with this add-in, then switch to the app and the code block formatting is applied there OK. It may take a minute or so to sync though. 

OneNote desktop can be downloaded from [here](https://www.onenote.com/download)
