### ISSUE TITLE
feature request: keyboard shortcut

### ISSUE THREAD

**Issue by Z1Wu** [elvirbrk/NoteHighlight2016#75]
The add-on is very awesome, but I wonder if it is possible to add some features such as inserting a code block by some keyboard shortcut just like using ` ``` ` to add code block in markdown file or using ` Alt + `  to edit equation. I am not sure if there are already some existing methods to achieve such functionality. If there were, it would be very helpful to leave the methods in the comment.

**Comment by elvirbrk** [comment]
Thanks for suggestion, I'll check to see if it's possible to enable something like that.

**Comment by vivenkyan** [comment]
I think until it's implemented you can put the languages you often use in Quick Access Toolbar and then use **Alt+ Position of the item** as shortcut.

Here's is what I mean:

![image](https://user-images.githubusercontent.com/6823372/54859667-2b355900-4d36-11e9-9490-36a7b57dae10.png)

So for me it's Alt+8 for Python and Alt+9 for C++.

**Comment by Z1Wu** [comment]
@vivenkyan Yeah, it is a convenient workaround. Thank you for your reply.

**Comment by elvirbrk** [comment]
Unfortunately, there is no option to create custom keyboard shortcuts, so workaround suggested by @vivenkyan is basically only option.
