### ISSUE TITLE
Can it support custom font family, font size?

### ISSUE THREAD

**Issue by talentwill** [elvirbrk/NoteHighlight2016#76]
if not, can you add this feature?  can it set table border color also? There is no table border currently. 
Can it save the last style config? so that we don't need to set the style every time.

**Comment by elvirbrk** [comment]
For custom font and size please see #22 and #32 
Table borders are not currently supported, but I will add it to TODO list.
Last used style used to be saved, I have to check if there is some bug.

**Comment by elvirbrk** [comment]
Supported in v3.6
