### ISSUE TITLE
OneNote for Windows 10 (2018 Standard), v.s. OneNote 2016

### ISSUE THREAD

**Issue by jtrcoonz** [elvirbrk/NoteHighlight2016#78]
I've seen other Issue posts but I'm not quite sure I saw a solid answer. Currently, the 2016 version of OneNote is no longer being updated and is not the Windows standard on office install anymore. I'm wondering if this add-on works for the current OneNote for Windows 10 (2018) as well. Has it been tested on it to see if it works? The new OneNote has tons of additional functionality and integration with other Microsoft services that allow it to be very useful that the 2016 version does not have. If it isn't possible, I understand, I just want to know if it is before I attempt to download and install it. Thank you!

**Comment by elvirbrk** [comment]
Unfortunately OneNote for Windows 10 (2018) doesn't support add-ons so it is not possible to use this add-on with that version.
We'll have to wait and see if Microsoft plans to add that feature.

**Comment by jtrcoonz** [comment]
Ok! Thank you for getting back to me. It's a great feature so I'm glad people will get some use out of it!
