### ISSUE TITLE
Won't install on Windows 10 1803

### ISSUE THREAD

**Issue by EricHerlitz** [elvirbrk/NoteHighlight2016#80]
Hi, the software installer fires up the Windows Installer Service but no GUI is shown or any installation ever occurs.

And after waiting like one hour nothing still have happened. Trying to install as local admin, .net 4.5 and 4.7 is installed

**Comment by elvirbrk** [comment]
Hm, well installation definitely isn't suppose to take that long.
I'm running it on 1803, so I don't think that is causing it. Also, add-in is targeted for .net 4.5.
Since everything should work, but it doesn't, maybe you can try to run installer from command line using msiexec.exe. Maybe it will show some error that will help with diagnosing issue.

**Comment by EricHerlitz** [comment]
Mainly getting errors like this 
![image](https://user-images.githubusercontent.com/1911851/49618874-78293580-f9ba-11e8-8e13-636771a3c5bb.png)

Running msiexec.exe /i "C:\Users\eric\Downloads\OnetasticInstaller.x86.exe" /l*v "c:\Temp\onetastic.log" will return the following to the log
`=== Verbose logging started: 2018-12-07  00:57:00  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\system32\msiexec.exe ===
MSI (c) (B4:90) [00:57:00:491]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (B4:90) [00:57:00:491]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (B4:50) [00:57:00:505]: Resetting cached policy values
MSI (c) (B4:50) [00:57:00:505]: Machine policy value 'Debug' is 0
MSI (c) (B4:50) [00:57:00:505]: ******* RunEngine:
           ******* Product: C:\Users\eric\Downloads\OnetasticInstaller.x86.exe
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (B4:50) [00:57:00:507]: Note: 1: 2203 2: C:\Users\eric\Downloads\OnetasticInstaller.x86.exe 3: -2147286960 
MSI (c) (B4:50) [00:57:00:507]: MainEngineThread is returning 1620
=== Verbose logging stopped: 2018-12-07  00:57:00 ===

`

**Comment by EricHerlitz** [comment]
It was probably another process hanging up the installation, after waiting a few days and a few reboots the installer worked just fine. Thanks
