### ISSUE TITLE
NoteHighlight2016.msi (Vestion 3.5) is recognized as malware by VirusTotal 

### ISSUE THREAD

**Issue by zeevb-work** [elvirbrk/NoteHighlight2016#84]
The NoteHighlight2016.msi for [version 3.5](https://github.com/elvirbrk/NoteHighlight2016/releases/download/v3.5/NoteHighlight2016.msi) is recognized as malware by one engine (MalwarePatrol) at VirusTotal. See [VirusTotal report](https://www.virustotal.com/#/url/365ae1f8e2273d5b050a338487d0a9b2f3292cb52df4d56f41a5095108b00f1d/detection)

**Comment by elvirbrk** [comment]
I run Reanalyze and now it's reported as clean: https://www.virustotal.com/#/url/365ae1f8e2273d5b050a338487d0a9b2f3292cb52df4d56f41a5095108b00f1d/detection
Anyway, if you have any doubts, just download source code and build it yourself ;)

**Comment by MateuszStepniak** [comment]
Similar story. I tried installing the add-on and highlight.exe was flagged as malicious by 3 engines. 
![image](https://user-images.githubusercontent.com/2552402/203567307-06edf651-4919-47cc-bc28-ec3ccf9ae89a.png)

![image](https://user-images.githubusercontent.com/2552402/203567189-cc90b803-4be9-491b-bcb9-f6591e91f9f6.png)
