### ISSUE TITLE
Edited Ribbon.xml and now it doesn't load

### ISSUE THREAD

**Issue by towerbe** [elvirbrk/NoteHighlight2016#86]
I edited the ribbon.xml file to enable a couple more languages and disable a few.  Now nothing loads at all.  I've checked the XML and it is fine.  Any clues?

**Comment by elvirbrk** [comment]
Try with original ribon.xml from here to see if it will fix the issue:
https://github.com/elvirbrk/NoteHighlight2016/blob/master/NoteHighlightAddin/ribbon.xml

Maybe it's some invisible formatting issue, like new line character, etc.

**Comment by towerbe** [comment]
Thanks, Elvir. I just tried to rearrange the order of buttons, and couldn't find any errors, but it failed multiple times.
